"""new columns

Revision ID: 3be6e8a04516
Revises: e5ddfda29211
Create Date: 2025-10-07 18:36:20.037275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be6e8a04516'
down_revision: Union[str, Sequence[str], None] = 'e5ddfda29211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('salesman_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_link')
    op.drop_column('products', 'salesman_count')
    # ### end Alembic commands ###
